[outputFormats]
    [outputFormats.manifest]
        name = "manifest"
        baseName = "site"
        mediaType = "application/manifest+json"
        notAlternative = "true"
    [outputFormats.browserconfig]
        name = "browserconfig"
        baseName = "browserconfig"
        mediaType = "application/xml"
        notAlternative = "true"

[outputs]
    home = [ "HTML", "RSS", "MANIFEST", "BROWSERCONFIG"]

